spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    address:
      admin: rjf654@gmail.com
  jwt:
    key: ${JWT_SECRET_KEY} #1234567890abcdefghijklmnopqrstuvwxyz (성원맥북Key)
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420